/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Conekta from '@cuidamimascota/react-native-conekta';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--'
  };
  componentDidMount() {
    const conekta = new Conekta();
    conekta.setPublicKey('key_KJysdbf6PotS2ut2');

    conekta.createToken({
      cardNumber: '4242424242424242',
      name: 'test',
      cvc: '123',
      expMonth: '12',
      expYear: '2021'
    }, (data) => {
        this.setState({
          status: 'native callback received',
          message: data.id
        });
    }, (error) => {
        this.setState({
          status: 'native callback received',
          message: error.code
        });
    })
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Conekta example</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>NATIVE CALLBACK MESSAGE</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
